release: Chromium 31.0.1650 (31.0.1650.9)
Compare: https://github.com/chromium/chromium/compare/e4308358b99d835c3fabaf05e2801b32d699b4bf...3a6a9a34b4b3eea04c3ef652ba031dfec2f89615

diff --git a/build/android/adb_profile_chrome b/build/android/adb_profile_chrome
--- a/build/android/adb_profile_chrome
+++ b/build/android/adb_profile_chrome
@@ -22,6 +22,8 @@ usage() {
   echo "                     (Default is /sdcard/Download/chrome-profile-results-*)"
   echo "  --categories|-c C  Select categories to trace with comma-delimited wildcards."
   echo "                     e.g. '*', 'cat1*,-cat1a'. Default is '*'."
+  echo "  --continuous       Using the trace buffer as a ring buffer, continuously"
+  echo "                     profile until stopped."
   echo "  --stop             Stop profiling."
   echo "  --download|-d      Download latest trace."
   echo "  --time|-t N        Profile for N seconds and download the resulting trace."
@@ -41,14 +43,45 @@ send_intent() {
 }
 
 download_latest_trace() {
-  TRACE_FILE=$(adb logcat -d | \
-      grep "Logging performance trace to file: " | \
-      tail -1 | \
-      perl -pi -e "s/.*\/storage\/emulated\/.+\/([^\r]+).*/\/sdcard\/Download\/\\1/g")
-  if [ -z "$TRACE_FILE" ]; then
-    echo "Unable to determine trace file name"
-    exit 1
-  fi
+  (adb logcat -d | grep -q "Logging performance trace to file") || {
+    echo "WARNING: Trace start marker not found. Is the correct version of Chrome running?"
+  }
+
+  local ITERATION=0
+  while true; do
+    # Chrome logs two different messages related to tracing:
+    #
+    # 1. "Logging performance trace to file [...]"
+    # 2. "Profiler finished. Results are in [...]"
+    #
+    # The first one is printed when tracing starts and the second one indicates
+    # that the trace file is ready to be downloaded.
+    #
+    # We have to look for both of these messages to make sure we get the results
+    # from the latest trace and that the trace file is complete. This is done by
+    # first looking for the last instance of the first message and then checking
+    # for the second message in the remaining part of the log.
+    TRACE_FILE=$(adb logcat -d | \
+        tac | \
+        grep --max-count=1 --before-context=100000 "Logging performance trace to file" | \
+        tac | \
+        grep "Profiler finished[.] Results are in " | \
+        perl -pi -e "s{.*/storage/emulated/.+/([^\r]+)[.].*}{/sdcard/Download/\\1}g")
+    if [ -n "$TRACE_FILE" ]; then
+      break
+    fi
+    if [ $ITERATION -eq 0 ]; then
+      echo -n "Waiting for Chrome to finish tracing..."
+    else
+      echo -n "."
+    fi
+    let ITERATION=ITERATION+1
+    if [ $ITERATION -eq 60 ]; then
+      echo "Timed out"
+      exit 1
+    fi
+    sleep 1
+  done
 
   adb pull $TRACE_FILE 2> /dev/null
   LOCAL_TRACE_FILE=$(basename $TRACE_FILE)
@@ -110,6 +143,7 @@ while test -n "$1"; do
       CATEGORIES="-e categories '$2'"
       shift
       ;;
+    --continuous) CONTINUOUS="-e continuous ." ;;
     -t|--time)
       shift
       if [ -z "$1" ] ; then
@@ -131,9 +165,9 @@ if [ -z "${INTERVAL}" ] ; then
   if [ -z "${FUNCTION}" ] ; then
     usage
   else
-    send_intent ${PACKAGE} ${FUNCTION} ${OUTPUT} ${CATEGORIES}
+    send_intent ${PACKAGE} ${FUNCTION} ${OUTPUT} ${CATEGORIES} ${CONTINUOUS}
   fi
 else
-  do_timed_capture ${PACKAGE} ${INTERVAL} ${CATEGORIES}
+  do_timed_capture ${PACKAGE} ${INTERVAL} ${CATEGORIES} ${CONTINUOUS}
 fi
 exit 0
